# -------------------------------------------------
# .bashrc Configuration
# -------------------------------------------------

# ----- PATH Configuration -----
# Add custom and standard binary locations to PATH
PATH="$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/usr/games:/sbin:$HOME/bin:$HOME/.local/bin"

# Only apply settings if bash is running interactively
case $- in
    *i*) ;;
    *) return;;
esac

# ----- Color Support & Aliases -----
# Enable color support and set related aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    # Fix other writable color
    LS_COLORS+=':ow=01;33'
fi

# # More ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# Load Blesh for enhanced interactive shell experience
if [[ -f /usr/share/blesh/ble.sh ]] && [[ ! -f ~/.bash-normal ]] && [[ $TERM != linux ]]; then
    source /usr/share/blesh/ble.sh --noattach
    
    #GRC-RS Configuration for colorizing command outputs
    GRC_ALIASES=true
    GRC="/usr/bin/grc-rs"
    if tty -s && [ -n "$TERM" ] && [ "$TERM" != "dumb" ] && [ -n "$GRC" ]; then
        alias colourify="$GRC"
        alias ant='colourify ant'
        alias blkid='colourify blkid'
        alias configure='colourify configure'
        alias df='colourify df'
        alias diff='colourify diff'
        alias dig='colourify dig'
        alias dnf='colourify dnf'
        alias docker-machinels='colourify docker-machinels'
        alias dockerimages='colourify dockerimages'
        alias dockerinfo='colourify dockerinfo'
        alias dockernetwork='colourify dockernetwork'
        alias dockerps='colourify dockerps'
        alias dockerpull='colourify dockerpull'
        alias dockersearch='colourify dockersearch'
        alias dockerversion='colourify dockerversion'
        alias du='colourify du'
        alias fdisk='colourify fdisk'
        alias findmnt='colourify findmnt'
        alias go-test='colourify go-test'
        alias ifconfig='colourify ifconfig'
        alias iostat_sar='colourify iostat_sar'
        alias ip='colourify ip'
        alias ipaddr='colourify ipaddr'
        alias ipneighbor='colourify ipneighbor'
        alias iproute='colourify iproute'
        alias iptables='colourify iptables'
        alias irclog='colourify irclog'
        alias iwconfig='colourify iwconfig'
        alias kubectl='colourify kubectl'
        alias last='colourify last'
        alias ldap='colourify ldap'
        alias lolcat='colourify lolcat'
        alias lsattr='colourify lsattr'
        alias lsblk='colourify lsblk'
        alias lsmod='colourify lsmod'
        alias lsof='colourify lsof'
        alias lspci='colourify lspci'
        alias lsusb='colourify lsusb'
        alias mount='colourify mount'
        alias mtr='colourify mtr'
        alias mvn='colourify mvn'
        alias netstat='colourify netstat'
        alias nmap='colourify nmap'
        alias ntpdate='colourify ntpdate'
        alias ping='colourify ping'
        alias ping2='colourify ping2'
        alias proftpd='colourify proftpd'
        alias pv='colourify pv'
        alias semanageboolean='colourify semanageboolean'
        alias semanagefcontext='colourify semanagefcontext'
        alias semanageuser='colourify semanageuser'
        alias sensors='colourify sensors'
        alias showmount='colourify showmount'
        alias sockstat='colourify sockstat'
        alias ss='colourify ss'
        alias stat='colourify stat'
        alias sysctl='colourify sysctl'
        alias tcpdump='colourify tcpdump'
        alias traceroute='colourify traceroute'
        alias tune2fs='colourify tune2fs'
        alias ulimit='colourify ulimit'
        alias uptime='colourify uptime'
        alias vmstat='colourify vmstat'
        alias wdiff='colourify wdiff'
        alias yaml='colourify yaml'
    fi

    # Color settings for GCC outputs
    export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

    # Use bat for cat if available
    if [ -f /usr/bin/bat ]; then
        alias cat='bat --paging=never --style=plain'
    fi
fi

# ----- History Configuration -----
HISTCONTROL=ignoreboth  # Prevent saving commands that start with a space and duplicates
shopt -s histappend     # Append history rather than overwrite
HISTSIZE=1000           # Store up to 1000 commands in memory
HISTFILESIZE=2000       # Store up to 2000 commands in history file
shopt -s checkwinsize   # Automatically adjust window size after each command

# Load custom aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# ----- NVM Configuration -----
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Auto completion Configuration
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# FZF Configuration
if [ -f /usr/share/fzf/key-bindings.bash ]; then
    eval "$(fzf --bash)"
    # using ripgrep combined with preview
    # find-in-file - usage: fif <searchTerm>
    fif() {
    if [ ! "$#" -gt 0 ]; then echo "Need a string to search for!"; return 1; fi
    fzf --preview "highlight -O ansi -l {} 2> /dev/null | rga --ignore-case --pretty --context 10 '$1' {}" < <(rga --files-with-matches --no-messages "$1")
    }
fi

# Attach Blesh with oh my posh if available
if [[ ${BLE_VERSION-} ]]; then
    ble-attach
    # FZF Configuration
    if [ -f /usr/share/fzf/key-bindings.bash ]; then
        _ble_contrib_fzf_base=/usr/share/fzf/
    fi
else
    # tty
    if [[ $TERM = linux ]]; then
        PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    else
        # bash-normal
        greenBg="\[\e[48;5;115m\]"
        greenFg="\[\e[38;5;115m\]"

        blackFg="\[\e[30m\]"
        whiteFg="\[\e[37m\]"

        # Reset
        fmtReset="\[\e[0m\]"

        systemBg="\[\e[48;5;237m\]"
        systemFg="\[\e[38;5;237m\]"

        nameBg="\[\e[48;5;248m\]"
        nameFg="\[\e[38;5;248m\]"

        # one line PS1
        PS1="$systemBg$greenFg   $systemFg$greenBg $blackFg$greenBg\w $fmtReset$greenFg$fmtReset "
    fi
fi
